name: ZB-GW03 Zigbee
device: EFR32MG21A020F768IM32
base_project: src/zigbee_ncp
filename: "{manifest_name}_{ezsp_version}"
sdk: "gecko_sdk:4.5.0"
toolchain: "12.2.1.20221205"

gbl:
  fw_type: zigbee_ncp
  ezsp_version: dynamic
  baudrate: 115200

sdk_extension:
  - id: xncp
    version: 1.0.0
  - id: xncp_common
    version: 1.0.0

add_components:
- id: xncp_core
  from: xncp
- id: xncp_common_commands
  from: xncp_common

c_defines:
  XNCP_MFG_MANUF_NAME: '"eWeLink"'
  XNCP_MFG_BOARD_NAME: '"ZB-GW03"'
  XNCP_BUILD_STRING: template:"{now:%Y%m%d%H%M%S}"
  XNCP_MANUAL_SOURCE_ROUTE_TABLE_SIZE: 200

  EMBER_APS_UNICAST_MESSAGE_COUNT: 32
  EMBER_BINDING_TABLE_SIZE: 32
  EMBER_BROADCAST_TABLE_SIZE: 64
  EMBER_KEY_TABLE_SIZE: 12
  EMBER_MAX_END_DEVICE_CHILDREN: 32
  EMBER_PACKET_BUFFER_COUNT: 255
  EMBER_SOURCE_ROUTE_TABLE_SIZE: 200

  EMBER_CHILD_TABLE_SIZE:
    type: c_flag
    value: 32

  EMBER_ROUTE_TABLE_SIZE:
    type: c_flag
    value: 250

  SL_IOSTREAM_USART_VCOM_BAUDRATE: 115200
  SL_IOSTREAM_USART_VCOM_FLOW_CONTROL_TYPE: usartHwFlowControlNone

  SL_IOSTREAM_USART_VCOM_PERIPHERAL: USART0
  SL_IOSTREAM_USART_VCOM_PERIPHERAL_NO: 0

  SL_IOSTREAM_USART_VCOM_TX_PORT: gpioPortB
  SL_IOSTREAM_USART_VCOM_TX_PIN:  1

  SL_IOSTREAM_USART_VCOM_RX_PORT: gpioPortB
  SL_IOSTREAM_USART_VCOM_RX_PIN:  0

  SL_IOSTREAM_USART_VCOM_CTS_PORT: gpioPortD
  SL_IOSTREAM_USART_VCOM_CTS_PIN:  3

  SL_IOSTREAM_USART_VCOM_RTS_PORT: gpioPortD
  SL_IOSTREAM_USART_VCOM_RTS_PIN:  4

  SL_IOSTREAM_USART_VCOM_RX_BUFFER_SIZE: 128